version: '3.8'

volumes:
  dbdata:

services:
  db:
    image: postgis/postgis:12-3.1-alpine
    ports:
      - 5433:5432
    environment:
      # env vars specific to postgres image used on first boot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # env vars useful for our sql scripts
      ADMIN_PASS: admin_password
      PGRST_PASS: postgrest_password
    volumes:
      - "./db_setup:/docker-entrypoint-initdb.d"
      - dbdata:/var/lib/postgresql/data
  api:
    image: postgrest/postgrest:v7.0.1
    ports:
      - "3031:3000"
    environment:
      PGRST_DB_URI: postgres://postgrest:postgrest_password@db:5432/public_data
      PGRST_DB_SCHEMA: ibge_v1 
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3031
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://127.0.0.1:3031