
CREATE DATABASE public_data OWNER db_admin;

\c public_data

CREATE SCHEMA ibge AUTHORIZATION db_admin;
CREATE SCHEMA ibge_v1 AUTHORIZATION db_admin;

CREATE EXTENSION postgis;

-- ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;